apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - repository.yaml
  - release.yaml
  - namespace.yaml
  - clustersecretstore.yaml
 # - externalsecret.yaml
  #- az-secrets.yaml
  #- deployment-crds.yaml
