apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets1
resources:
  - repository.yaml
  - release.yaml
  - namespace.yaml
  - clustersecretstore.yaml
  - externalsecret.yaml
  - az-secrets.yaml
