apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1000 #applied to volume mount
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.25.0
        ports:
        - containerPort: 3005
      #  volumeMounts:
      #    - name: linkding-data
       #     mountPath: /etc/linkding/data
      #  securityContext:
      #    allowPrivilegeEscalation: false
        envFrom:
          - configMapRef:
            name: audiobookshelf-env.yaml
      #    - secretRef:
       #       name: linkding-secret
      #volumes:
     # - name: linkding-data
      #  persistentVolumeClaim:
      #    claimName: linkding-data-pvc