apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blinko
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - blinko-ingress.yaml
  - blinko-configmap.yaml
  - blinko-database-secret.yaml
