apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  homepage
resources:
  - deployment.yaml
  - storage.yaml
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
 
