apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:WdDWwxnyGAImRW0tpgAM4g==,iv:jcCCQO6NdEZWE+pvkE8Sfg6D1SWG0cAv8xDPJfz/cjo=,tag:9t1LlLNBqmVAiQYe+tOFLQ==,type:str]
    adminUser: ENC[AES256_GCM,data:FNNcFJYXM2E=,iv:ZPADW5pnSdInIODEI4Pf9MD/Y6CpUkLY4upc0PlJ8mo=,tag:aDrr0056EucaF0Pm9HIpjg==,type:str]
kind: Secret
namespace: monitoring
metadata:
    creationTimestamp: null
    name: grafana-secret
sops:
    age:
        - recipient: age15nh307szugl4u5hp65zgy9fm2cyqd35mlnawusl768g47n420e7sdrrsge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRng1MVV2MXljVmhLdU04
            TFhSSW00SWo1cGJZN1pPcUFLNGZRblllUVVjCk5yMFRRODQ2cmpaY3pCd21zVmJR
            bzluVU5vVTYzdlNtMGpGaU5Fa3dxQzgKLS0tIFBnZ2k5bTR3bTBFRUV2RGtsR0VL
            Z2Rpbzc5Wm9FaU9TNXE5Rmp2SnFvL0EKKtr3e16yQeibFXSXCsBoWfWJkaYj+ahJ
            HqXB4k4Ltcw6R0IYGVZam91tM9f9Ls4VD4wWgWbdJ050bYxCMSW8Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T19:08:07Z"
    mac: ENC[AES256_GCM,data:xxo3gN5eryIcagnyRY9ORhHjqMYGMXA3tXPrYRBPh0nH8rda8QTdz1ANfBbLkDWfIqx5T+4Y0uNqY0aMNwLHGl51AAbx2EU8J3UQ7hHvj3SEalR0Dx1JUvu9zUIi+WBuh0Gh0T5bda6NYhQJcVj4a1HPdKtre6PqcrZbXeaQF58=,iv:6hdgCg9IWS+LA/EYaqarOgNxCwtLxX3CtWWlYFLy80Q=,tag:TadysXCr2Js6VA8S0002hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2