apiVersion: v1
data:
  adminPassword: ENC[AES256_GCM,data:oEDM6+1XwQ6CSlfmqZQp3w==,iv:/xak2u/ujZ/o9dhSP69Kw0Gbj9zyN8bqbnpoCBq6WZU=,tag:qZCWMGJx+Q6OJ/xxXwj1rw==,type:str]
kind: Secret
namespace: monitoring
metadata:
    creationTimestamp: null
    name: grafana-secret
sops:
    age:
        - recipient: age15nh307szugl4u5hp65zgy9fm2cyqd35mlnawusl768g47n420e7sdrrsge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUnR1UFBKeFRLRVFTRlcz
            S2NReGhBRDlCcHBqWTdiLzNXVHY2b1pRN1VzCkhJUzY3cSs3T0JMcWIvZHBBb1NL
            aVdYWVhiVlBpQlNQOXZ1aWwzS0pRS1UKLS0tIHBFdGRFOGNtMzBoUEhsWlE2UW9C
            UVgvYXllWlVpWUNyMkNhSGlSeDFMOWMKkdhPePPAGPikBGXmy7ot/Wa4kd/EQC9q
            +N1pG3IrYWJY9yQeYw/jrRecOmjnC3tQ+G+rUbbV4LARSzQNqCQFDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T18:45:24Z"
    mac: ENC[AES256_GCM,data:4XU5gxwhQJILJ4fGjC1ppDCwxvMs0Nwq7w3NJe786crhXPCRPmY1u16OmlQwuvYEKN4Ib4zp2PShzYJlANoSz2fxBzVD7nwth3AKlWt95rnnp3TtEKcz/+dr4oD5jBfJcU5+0OkY7y+3kTiepkOKO9eYnIY4RfwSGwAMWT5YwhM=,iv:UjOIRvvFYoN77FMrAS9MNAGEokLMI6STls76ecFRl/A=,tag:/MSQ7gNTJND/z4ofU3jLxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2