#this is an actual helm repo installation
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: monitoring
spec:
  interval: 30m # check every 30min if an update is there
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '66.2.2'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install: #when you install this stack it comes with its own custom CRD - custom resource definitions
    crds: Create #below is whats needed for the stack to run correctly after update
  upgrade: #when upgrade is detected
    crds: CreateReplace #create new ones or replace the existing one
  driftDetection: #this is for flux to revert changes after you set them up manually to the state it is in a helm repo
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: mischa