apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '75.6.1'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-monitoring
      interval: 12h
  values:
    replicaCount: 2