#this is an actual helm repo installation
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: monitoring
spec:
  interval: 30m # check every 30min if an update is there
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '75.6.1'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-monitoring
      interval: 12h
  install: #when you install this stack it comes with its own custom CRD - custom resource definitions
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: mischa