apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - deployment.yaml
  - storage.yaml
  - namespace.yaml
  - service.yaml
  - linkding-ingress.yaml
  - linkding-configmap.yaml
  - linkding-database-secret.yaml
  #- externalsecret.yaml
