apiVersion: v1
data:
  LD_DB_ENGINE: postgres
  LD_DB_DATABASE: app
  LD_DB_USER: app
  LD_DB_HOST: postgresql-rw.database.svc.cluster.local
  LD_DB_PORT: "5432"
kind: ConfigMap
metadata:
  name: linkding-database